Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,37 +1,31 @@
+---
 name: CI + CD Pipeline
-
 on:
   pull_request:
     branches:
       - dev
       - main
-
   push:
     branches:
       - main
-
 jobs:
   ci:
     runs-on: ubuntu-latest
-
     steps:
-       - name: Checkout
-         uses: actions/checkout@v4
-       - name: Validate HTML
-         run: |
-           if [ -f index.html ]; then
-             echo "CI passed"
-           else
-             echo "CI failed"
-             exit 1
-           fi
-
-   cd:
-     runs-on: ubuntu-latest
-     needs: ci
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Validate HTML
+        run: |
+          if [ -f index.html ]; then
+            echo "CI passed"
+          else
+            echo "CI failed"
+            exit 1
+          fi
+  cd:
+    runs-on: ubuntu-latest
+    needs: ci
   if: github.event_name == 'push'
-
   steps:
-     - name: Deploy simulation
-       run: echo "CD running"
-  
+    - name: Deploy simulation
+      run: echo "CD running"
